### ISSUE TITLE
Request: How can I avoid VSCode underlines when I use table.indexOfElement

### ISSUE THREAD

**Issue by adamtheturtle** [notpeter/playdate-luacats#5]
Thank you for this project. It has solved many incorrectly reported type errors for me.

However, when I use `table.indexOfElement` in VSCode, I still get `accessing undefined field 'indexOfElement' of global 'table'`. How can I avoid this error?

**Comment by notpeter** [comment]
Hi,

1. Which git rev of playdate-luacats are you using (please `git pull`)
2. Are you see in this in VSCode or getting that at runtime?
3. Did you perhaps accidentally create your own variable called `table`? (overwriting the playdate API provided `table` global variable)

Otherwise, works for me.
<img width="713" alt="Screenshot 2024-03-21 at 21 20 10" src="https://github.com/notpeter/playdate-luacats/assets/145113/3e44ae3b-2616-4328-ac53-2ec33e50377d">

<img width="501" alt="image" src="https://github.com/notpeter/playdate-luacats/assets/145113/5fa6f0bc-10f2-4d80-b8b9-f3d3869df4d4">

**Comment by adamtheturtle** [comment]
Hi @notpeter .

Apologies! The error was from `vscode-luacheck`, not from the language server.
